import 'package:dataproject2/datamodel/LocationModel.dart';
import 'package:shared_preferences/shared_preferences.dart';

class AppConfig {
  /// SharedPrefs
  static late SharedPreferences prefs;

  /// Location List
  static List<LocationModel> locationList = [];

  /// KEYS
  static const AppName = 'BK International';
  static const AppName2 = 'KGC';

  /// API's  //http://103.141.115.18:24977/api/SaleEnq/
  //static const String baseUrl = 'http://103.141.115.18:24976/bkintl/public/';
  static const String baseUrl = 'http://103.204.185.17:24976/bkintl/public/';
  static const String baseUrl2 = 'http://103.204.185.17:24977/api/';
  static const String baseUrlproduction = 'http://103.204.185.17:24977/api/';
  static const String addToken = 'api/add/device';
  static const String removeToken = 'api/delete/device';
  static const String getCompany = 'api/quotation/company';
  static const String getCompanyMI =
      'http://103.204.185.17:24977/webapi/api/Common/';

  static const String getParty = 'api/parties';
  static const String getAddressList = 'api/address_lists';
  static const String addUploadAttachment = 'api/upload_attachment';
  static const String getQtNumber = 'api/max_qtn_number';
  static const String saveQuotations = 'api/save_quotations';
  static const String editQuotation = 'api/quotation/edit';
  static const String viewCatalogPdf = 'api/catalog_file';
  static const String deleteQuotation = 'api/quotation/delete';
  static const String full_image = "${baseUrl}uploads/company/";
  static const String small_image = "${baseUrl}uploads/company/512*512/";
  static const String trackerList = "api/tracker_list";
  static const String refreshAlerts = "api/refresh_notification_list";
  static const String getImages = "api/save_item_image/";
  static const String uploadItemImages = "api/upload_item_image";
  static const String searchQuotation = "api/quotation/search";
  static const String viewQuotation = "api/quotation/detail";
  static const String searchItemParameters = "api/search_item_parameters";
  static const String getSubCategory = "api/get_sub_category";
  static const String searchItems = "api/search_items";
  static const String getItemDetails = "api/item_details";
  static const String getTrackerDetails = "api/tracker_detail";
  static const String getTrackerCount = "api/tracker_counts";
  static const String getCatalogItemParameters = 'api/catalog_item_parameters';
  static const String getCatalogDetailsById = 'api/catalog_details';
  static const String saveCatalogImages = 'api/save_catalog_images';
  static const String saveQtnDetails = 'api/save_quotation_dtl';
  static const String listLocations = 'api/list_locations';
  static const String factoryUsers = 'api/get_factories_users';
  static const String updateFactoryUser = 'api/update_user_factory';
  static const String catalogStockDetails = 'api/catalog_stock_details';
  static const String purchasePlanRate = 'api/catalog_purchase_plans';
  static const String salePlanRate = 'api/catalog_sale_plans';
  static const String catalogProcessPlans = 'api/catalog_process_plans';
  static const String mapToCatalog = 'api/map_catalog_machine';
  static const String addMachineType = 'api/add_machine_type';
  static const String addMachine = 'api/add_machine_master';
  static const String deleteCatalogMachineImage = 'api/delete_catalog_machine';
  static const String updateCatalogImage = 'api/edit_catalog_images';
  static const String blockUnBlockCatalog = 'api/map_block_catalog';
  static const String getMailMessage = 'api/get_sale_message';
  static const String sendMail = 'api/send_sale_message';
  static const String MACHINE_MASTER = '1';
  static const String contactList = 'api/list_contacts';
  static const String addContact = 'api/add_contact';
  static const String updateContact = 'api/edit_contact';
  static const String deleteContactImage = 'api/delete_contact_image';
  static const String gatePassCompany = 'api/indent_company';
  static const String getEmployeeList = 'api/list_employees';
  static const String getPartyList = 'api/list_parties';
  static const String getEmployeeCompanies = 'api/employees/companies';
  static const String getVisitorCompanies = 'api/visitors/companies';
  static const String getPendingEmpPass = 'api/pending_emp_pass';
  static const String getPendingVisitorPass = 'api/pending_visitor_pass';
  static const String updateEmployeePass = 'api/update_emp_pass';
  static const String updateVisitorPass = 'api/update_visitor_pass';
  static const String getApprovalUsers = 'api/list_approve_users';
  static const String submitEmpPass = 'api/add_emp_pass';
  static const String editEmpPass = 'api/edit_emp_pass';
  static const String submitVisitorPass = 'api/add_visitors_pass';
  static const String searchEnquiry = 'api/enquiry/search';
  static const String addEnquiry = 'api/save_enquiry';
  static const String editEnquiry = 'api/enquiry/edit';
  static const String getEnquiryNo = 'api/max_enquiry_number';
  static const String getEnquiryDetail = 'api/enquiry/detail';
  static const String getEnquiryPreText = 'api/get_sale_enquiry_message';
  static const String sendSaleEnquiry = 'api/send_sale_enquiry_message';
  static const String smsList = 'api/sms_lists';
  static const String attendanceList = 'api/attendance_lists';
  static const String workMachine = 'api/work_machine_code';
  static const String getDailyProd = 'api/get_daily_prod_mp_plan';
  static const String getEmployeeDetails = 'api/employee/details';
  static const String updateProdMpPlan = 'api/update_prod_mp_plan';
  static const String getAllEmployee = 'api/employees/lists';
  static const String uploadEmployeePic = 'api/upload_employee_pic';
  static const String deleteEmployeePic = 'api/delete_employee_pic';
  static const String editEmployeePic = 'api/edit_employee_pic';
  static const String uploadUserPic = 'api/upload_profile_pic';
  static const String placeToVisit = 'api/list_gate_visit_locations';
  static const String personToMeet = 'api/visitor_person_meets';
  static const String contactVisitorSearch = 'api/get_visitor_address';
  static const String downloadSaleQtn = '${baseUrl2}SaleQtn/';
  static const String downloadSaleEnq = '${baseUrl2}SaleEnq/';
  static const String downloadVisitorGatePass = '${baseUrl2}VisitorGateEntry/';
  static const String downloadEmployeeGatePass = '${baseUrl2}EmployeeGatePass/';
  static const String sendVisitorOtp = 'api/send_visitor_otp';
  static const String getVisitorPassDetail = 'api/visitor_pass_details';
  static const String getEmployeePassDetail = 'api/view_emp_pass';
  static const String editVisitorPass = 'api/edit_visitor_pass';
  static const String gateEntryDocType = 'api/gatentry/doc_type';
  static const String gateEntryParties = 'api/gatentry/parties/new';
  static const String gateEntryPartiesItem = 'api/gatentry/parties/items/new';
  static const String gateEntrySave = 'api/gatentry/save';
  static const String packingOptions = 'api/packing/options';
  static const String packingParties = 'api/packing/parties';
  static const String packingPartiesItem = 'api/packing/parties/items';
  static const String packingSave = 'api/packing/save';
  static const String getPendingBill = 'api/bill/pending_bills';
  static const String getPendingBillDetail = 'api/bill/pending_items';
  static const String getSaleOrderDetail = 'api/saleorder/detail';
  static const String getIndentOrderDetail = 'api/indent/detail';
  static const String getGateEntryDetail = 'api/gatentry/detail';
  static const String getPackingDetail = 'api/packing/detail';
  static const String getPurOrderDetail = 'api/purchaseorder/detail';
  static const String approveBillItem = 'api/bill/item_approve';
  static const String approveBillCompanies = 'api/bill/companies';
  static const String employeeBlackList = 'api/employees/black_list';
  static const String uploadPurBillImage = 'api/bill/upload_image';
  static const String deletePurBillImage = 'api/bill/delete_image';
  static const String salaryEmployee = 'api/salary/employees';
  static const String viewEmployeeSalary = 'api/salary/view';
  static const String saveEmployeeSalary = 'api/salary/save';
  static const String getSalaryMonth = 'api/salary/month';
  static const String salaryAdvEmployee = 'api/advancesalary/emp_lists';
  static const String salaryViewAdvEmployee = 'api/advancesalary/view';
  static const String saveAdvanceSalary = 'api/advancesalary/save';
  static const String editAdvanceSalary = 'api/advancesalary/edit';
  static const String accountPartyList = 'api/parties/list';
  static const String fullAndFinalEmployees = 'api/full_salary/employees';
  static const String calculateSalary = 'api/salary/calculate';
  static const String accountPartyDetail = "api/parties/details";
  static const String approveParty = "api/parties/approve";
  static const String cashPartyDetail = "api/cash/parties_list";
  static const String cashReceiptSubmit = "api/receiptant/newentry";
  static const String cashSubmit = "api/cash/newentry";
  static const String receiptantPartyDetail = "api/receiptant/parties_list";
  static String pendingBillForPayments = "api/cash/pending_bills";
  static String pendingBillForReceipt = "api/receiptant/pending_bills";
  static const String paymentreceiptapproval = "api/cash/pending_payments";
  static const String cashreceiptapproval = "api/receiptant/pending_payments";
  static const String companydetailApiURl = "api/cash/pending_companies";
  static const String approveCashPayItem = "api/cash/approve_payment";
  static const String approveCashReceipt = "api/receiptant/approve_receipt";
  static const String companydetailRecApiURl =
      "api/receiptant/pending_companies";
  static const String getMail = 'api/cash/get_sale_message';
  static const String sendCashMail = 'api/cash/send_sale_message';
  static const String getTableDetails = 'api/cash/get_table_details';
  static const String cashPaymentDetail = 'api/cash/details';
  static const String cashDocDate = 'api/cash/validate_doc_date';
  static const String getDelete = 'api/cash/delete_item';
  static const String cashSave = 'api/cash/edit_details';
  static const String cashReceiptDetail = 'api/receiptant/details';
  static const String cashReceiptSave = 'api/receiptant/edit_details';
  static const String partyOptionList = 'api/parties/option_lists';
  static const String accountPartySave = 'api/parties/save';
  static const String accountPartyDelete = 'api/parties/section_delete';
  static const String getCashCompany = 'api/cash/companies';
  static const String getCashPayment = 'api/cash/payments';
  static const String getCashRecCompany = 'api/receiptant/companies';
  static const String getCashReceipt = 'api/receiptant/payments';
  static const String cashDelete = 'api/cash/delete';
  static const String getEmpSign = 'api/get_employee_sign';
  static const String uploadFingerPrint = 'api/upload_fingerprints';
  static const String findEmployeeByFingerprint = 'api/find_employee';
  static const String listOfFingerprint = 'api/list_fingerprints';
}

/// Keys
const Qtn = 'Quotation';
const saleEnquiry = 'SaleEnquiry';

/// Comp Keys
const COMP_KMT = '1';
const COMP_ITT = '2';
const COMP_BK = '3';
const COMP_BK99 = '99';
const COMP_BK98 = '98';
const COMP_KMT_OVERSEAS = '4';
