// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR9yEp-9UiM5hqQ-yN8XVF4Le5eIiXlSM',
    appId: '1:490495259121:web:6d7d7d5a59ce2e0d4f5450',
    messagingSenderId: '490495259121',
    projectId: 'bk-international',
    authDomain: 'bk-international.firebaseapp.com',
    databaseURL: 'https://bk-international.firebaseio.com',
    storageBucket: 'bk-international.appspot.com',
    measurementId: 'G-P3KY13LGST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUvLAlHBFCxTqPR9M_LbWODcTwJDlwt2A',
    appId: '1:490495259121:android:93492c16a88cb8434f5450',
    messagingSenderId: '490495259121',
    projectId: 'bk-international',
    databaseURL: 'https://bk-international.firebaseio.com',
    storageBucket: 'bk-international.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjXR1JmvXYIynh92B2D7zccEBNxw2RTk4',
    appId: '1:490495259121:ios:0519d7ba3b209c084f5450',
    messagingSenderId: '490495259121',
    projectId: 'bk-international',
    databaseURL: 'https://bk-international.firebaseio.com',
    storageBucket: 'bk-international.appspot.com',
    iosClientId: '490495259121-mp71adp62528egfkfjtc8v8r5s8fm47j.apps.googleusercontent.com',
    iosBundleId: 'pa.bkkinternational.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjXR1JmvXYIynh92B2D7zccEBNxw2RTk4',
    appId: '1:490495259121:ios:f55e9dc4075acfd74f5450',
    messagingSenderId: '490495259121',
    projectId: 'bk-international',
    databaseURL: 'https://bk-international.firebaseio.com',
    storageBucket: 'bk-international.appspot.com',
    iosClientId: '490495259121-0o06ao5rhm46uctfvjmqq8irh5d94oin.apps.googleusercontent.com',
    iosBundleId: 'packagename.bkInternational',
  );
}
